### ISSUE TITLE
Conflicting Leaflet packages

### ISSUE THREAD

**Issue by KyleKing** [fuatsengul/fuatsengul-leaflet-easybutton#1]
Thanks for porting over easyButton to a meteor package! I would like to use it, but I am already using bevanhunt:leaflet, which conflicts with the additional fuatsengul:leaflet package. Would you mind removing the dependency on the fuatsengul:leaflet package, so we can use any leaflet package?

**Comment by fuatsengul** [comment]
Hello Kyle,
OK, I did it, you can use it with another leaflet packages now.

**Comment by KyleKing** [comment]
Great! Thank you so much for updating it so quickly
